controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    position_proportional_gain: 10.0
    stopped_velocity_tolerance: 0.05
    allow_integration_in_goal_trajectories: true
    allow_nonzero_velocity_at_trajectory_end: true
    allow_partial_joints_goal: false
    joints:
      - rj_dg_1_1
      - rj_dg_1_2
      - rj_dg_1_3
      - rj_dg_1_4
      - rj_dg_2_1
      - rj_dg_2_2
      - rj_dg_2_3
      - rj_dg_2_4
      - rj_dg_3_1
      - rj_dg_3_2
      - rj_dg_3_3
      - rj_dg_3_4
      - rj_dg_4_1
      - rj_dg_4_2
      - rj_dg_4_3
      - rj_dg_4_4
      - rj_dg_5_1
      - rj_dg_5_2
      - rj_dg_5_3
      - rj_dg_5_4
      - lj_dg_1_1
      - lj_dg_1_2
      - lj_dg_1_3
      - lj_dg_1_4
      - lj_dg_2_1
      - lj_dg_2_2
      - lj_dg_2_3
      - lj_dg_2_4
      - lj_dg_3_1
      - lj_dg_3_2
      - lj_dg_3_3
      - lj_dg_3_4
      - lj_dg_4_1
      - lj_dg_4_2
      - lj_dg_4_3
      - lj_dg_4_4
      - lj_dg_5_1
      - lj_dg_5_2
      - lj_dg_5_3
      - lj_dg_5_4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
